### ISSUE TITLE
Provide 1mA current limit and enforce it in hardware

### ISSUE THREAD

**Issue by DemiMarie** [m-labs/ionpak#11]
My understanding is that an ionization gague current is typically measured in μA or below, so a current of over 1mA indicates a fault condition and the device should be shut down.  The only possible exception is at power-up, when parasitic capacitance needs to be charged.

More importantly, this provides a critical safety feature: by enforcing a 1mA current limit, the hazard of electric shock is significantly reduced, though by no means eliminated.

The limit should be enforced entirely in hardware.

**Comment by sbourdeauducq** [comment]
Which current? The emission current can definitely be higher than 1mA.

**Comment by DemiMarie** [comment]
Duh, sorry.  I was confused as to how ionization gagues worked.  Thank you!
