### ISSUE TITLE
Correct version of code posted?

### ISSUE THREAD

**Issue by bynars99** [m-labs/ionpak#14]
It looks like the currently posted code is an old version, corresponding to the Rev 1 hardware, since the code mentions three FBI range settings. It also looks like it has some values overridden with hardcoded ones, such as the fv_pwm_duty on line 100-101 in loop_cathode.rs.

Is it possible to get the latest code?

**Comment by sbourdeauducq** [comment]
There is no code for v2 hardware and probably never will, unless someone makes v2 hardware and writes it.
Currently we are working on v3 hardware with STM32, perhaps GaN resonant converters, PoE, and a number of other changes.
